Fix defer issue where some lines were not processed.
This caused the auto keyword to remain in place which manifested as:
error: expected identifier or '(' before ...